phrase:
  host: https://api.us.app.phrase.com/v2
  project_id: 88ffd4d5abd6494131fabb1a271950b8
  file_format: docx
  push:
    sources:
    - file: ./docx/stub_doc_en.docx
      params:
        locale_id: en
  pull:
    targets:
    - file: ./docx/doc_es.docx
      params:
        locale_id: es
        include_empty_translations: false (boolean) #Indicates whether keys without translations should be included in the output as well.
