phrase:
  host: https://api.us.app.phrase.com/v2
  project_id: 88ffd4d5abd6494131fabb1a271950b8
  file_format: i18next

  push:
    sources:
    - file: ./phrase_json/en.json
      params:
        locale_id: en

  pull:
    targets:
    - file: ./phrase_json/es.json
      params:
        locale_id: es
    - file: ./phrase_json/en.json
      params:
        locale_id: en
