phrase:
  host: https://api.us.app.phrase.com/v2
  project_id: 88ffd4d5abd6494131fabb1a271950b8
  file_format: DOCX

  push:
    sources:
    - file: ./docx/stub_doc_en.docx
      params:
        locale_id: en
        tags: REVIEW_NEEDED  #List of tags separated by comma to be associated with the new keys contained in the upload.

  pull:
    targets:
    - file: ./docx/doc_en.docx
      params:
        locale_id: en
    - file: ./docx/doc_es.docx
      params:
        locale_id: es
