phrase:
  host: https://api.us.app.phrase.com/v2
  project_id: 88ffd4d5abd6494131fabb1a271950b8
  push:
    sources:
    - file: ./docx/stub_doc_en.docx
      params:
        file_format: docx
  pull:
    targets:
    - file: ./docx/doc_es.docx
      params:
        file_format: docx
