name: Deploy to Github.io

on:
  push:
    branches:
      - prod

  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    env:
      PHRASE_DISCOVERY_ACCESS_TOKEN: ${{ secrets.PHRASE_DISCOVERY_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: Discovery-MkDocs
      - uses: actions/setup-python@v4
      - name: Setup Python
        run: |
          echo $PWD
          cd Discovery-MkDocs
          ls -l
          pip install --upgrade pip         
          pip install -r requirements.txt

      - name: Translate Docs
        run: |
          echo $PWD
          cd Discovery-MkDocs
          ls -l
          echo "Calling for phrase to translate to md"
          python phrase-translate-to-md.py markdown-docs

      - name: deploy to github.io
        if: github.ref == 'refs/heads/prod'
        shell: bash -l {0}
        run: |
          echo $PWD
          cd Discovery-MkDocs
          ls -l
          echo "mkdocs gh-deploy"
          python -m mkdocs gh-deploy --force
