name: Deploy to Github.io

on:
  push:
    branches:
      - prod

  workflow_dispatch:

jobs:
  build_and_deploy:

    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          path: Discovery-MkDocs

      - name: Setup Python
        env:
          PHRASE_DISCOVERY_ACCESS_TOKEN: ${{ secrets.PHRASE_DISCOVERY_ACCESS_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r Discovery-MkDocs/requirements.txt

      - name: deploy to github.io
        if: github.ref == 'refs/heads/prod'
        shell: bash -l {0}
        run: |
          echo $PWD
          cd Discovery-MkDocs
          ls -l
          python phrase-translate-to-md.py ../Discovery-MkDocs
          python -m mkdocs gh-deploy --force
