name: Deploy to Github.io
on:
  push:
    branches:
      - prod
      - test
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: Discovery-MkDocs

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Setup Python environment
        env:
          PHRASE_DISCOVERY_ACCESS_TOKEN: ${{ secrets.PHRASE_DISCOVERY_ACCESS_TOKEN }}
        working-directory: Discovery-MkDocs
        run: |
          pip install wheel -r requirements.txt
          python -m phrase-translate-to-md markdown-docs

      - name: Deploy to github.io
        if: github.ref == 'refs/heads/prod'
        working-directory: Discovery-MkDocs
        run: python -m mkdocs gh-deploy --force
